//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVT
    {
        public DVT()
        {
            this.MATHANGs = new HashSet<MATHANG>();
        }
    
        public int MADVT { get; set; }
        public string DVT1 { get; set; }
    
        public virtual ICollection<MATHANG> MATHANGs { get; set; }
    }
}
