//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        public MATHANG()
        {
            this.CTPXes = new HashSet<CTPX>();
        }
    
        public int MAHANG { get; set; }
        public string TENHANG { get; set; }
        public Nullable<int> MADVT { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    
        public virtual ICollection<CTPX> CTPXes { get; set; }
        public virtual DVT DVT { get; set; }
    }
}
