//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUATHANG()
        {
            this.CTPXes = new HashSet<CTPX>();
        }
    
        public int MAPHIEU { get; set; }
        public Nullable<int> MADL { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<decimal> SOTIENTRA { get; set; }
        public Nullable<decimal> CONLAI { get; set; }
        public Nullable<int> NGUOIXUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPX> CTPXes { get; set; }
        public virtual DAILY DAILY { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
