//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN
    {
        public QUAN()
        {
            this.DAILies = new HashSet<DAILY>();
        }
    
        public int MAQUAN { get; set; }
        public string TENQUAN { get; set; }
        public Nullable<int> SODLTOIDA { get; set; }
    
        public virtual ICollection<DAILY> DAILies { get; set; }
    }
}
