//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhieuXuat_NhanVien_DaiLy
    {
        public string TENNV { get; set; }
        public string TENDL { get; set; }
        public int MAPHIEU { get; set; }
        public Nullable<int> MADL { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<decimal> SOTIENTRA { get; set; }
        public Nullable<decimal> CONLAI { get; set; }
        public Nullable<int> NGUOIXUAT { get; set; }
    }
}
