//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhieuThu_NhanVien_DaiLy
    {
        public int MAPHIEU { get; set; }
        public Nullable<int> MADL { get; set; }
        public Nullable<System.DateTime> NGAYTHUTIEN { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public Nullable<int> NGUOITHU { get; set; }
        public string TENDL { get; set; }
        public string TENNV { get; set; }
    }
}
