//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCHUCVU_NHANVIEN_TAIKHOAN
    {
        public int MACHUCVU { get; set; }
        public string TENCHUCVU { get; set; }
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string TENDANGNHAP { get; set; }
        public string PASSWORD { get; set; }
    }
}
