//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDAILY_LOAIDL_QUAN
    {
        public int MADL { get; set; }
        public string TENDL { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYTIEPNHAN { get; set; }
        public Nullable<decimal> SONO { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        public string TENLOAI { get; set; }
        public string TENQUAN { get; set; }
    }
}
